print('=========Desafio 015========')
dias = float(input('Quantos dias alugados? '))
km = float(input('km rodados? '))
total = (60 * dias) + (0.15 * km)
print('O total a pagar é R$ {:.2f} '.format(total))
