dado = input('Digite algo: ')
print('Dado digitado {}'.format(dado))
print('Seu tipo é {}'.format(type(dado)))
print('É numerico: {}'.format(dado.isnumeric()))
print('É alfabetico: {}'.format(dado.isalpha()))
print('É alfanumerico: {}'.format(dado.isalnum()))
print('É maiusculo: {}'.format(dado.isupper()))
print('É minusculo: {}'.format(dado.islower()))
print('É um valor decimal: {}'.format(dado.isdecimal()))
print('É printavél: {}'.format(dado.isprintable()))
print('Só tem espaco: {}'.format(dado.isspace()))
print('É numérico ASCI: {}'.format(dado.isdigit()))
print('É Identificador valido: {}'.format(dado.isidentifier()))
print('É Capitalizado: {}'.format(dado.istitle()))

